name: Push Discord notification
on: release
defaults:
  run: 
    shell: pwsh

jobs:
  announce:
    name: Discord Announcement
    runs-on: ubuntu-latest
    steps:
      - name: Preparing
        run: |
					echo "HTML_URL=$(Invoke-RestMethod "https://api.github.com/repos/ImaterialC/PriconeTL/releases/latest" | Select-Object -ExpandProperty html_url)" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Announcing new release
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        with:
          args: "<@&967698392870436874> Aruji-sama, look like there is a new update dropped, why don't we check it out?`n`n${{ env.HTML_URL }}"
